name: MSVC Build
on: workflow_dispatch

env:
  BUILD_CONFIGURATION: Game__Shipping__Win64

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup github SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.UEPSEUDO_SSH_KEY }}
        known_hosts: unnecessary

    - name: Checkout SFV
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0 # needed to get commits since last tag
        ssh-key: ${{ secrets.UEPSEUDO_SSH_KEY }}
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: pwsh
      run: |
        .\Scripts\build_project.ps1
    
    - name: StandalonePackage
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: pwsh
      run: |
        .\Scripts\package_standalone.ps1

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: StriveFrameViewer_Standalone
        path: ${{github.workspace}}\Packages\Standalone\
        if-no-files-found: error

    - name: UnverumPackage
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: pwsh
      run: |
        .\Scripts\package_unverum.ps1

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: StriveFrameViewer_Unverum
        path: ${{github.workspace}}\Packages\Unverum\
        if-no-files-found: error


        
    